
// USER ACTION TYPES
export const INSERT_FAKE_JOE = "INSERT_FAKE_JOE";

// GOVE OFFCIAL ACTION TYPES
export const CHANGE_GOV_OFFICIAL = "CHANGE_GOV_OFFICIAL";

// CELEB ACTION TYPES
export const REMOVE_DOGE_LORD = "REMOVE_DOGE_LORD";